package rds_test

var DescribeDBInstancesExample1 = `
<DescribeDBInstancesResponse xmlns="http://rds.amazonaws.com/doc/2013-09-09/">
  <DescribeDBInstancesResult>
    <DBInstances>
      <DBInstance>
        <ReadReplicaDBInstanceIdentifiers/>
        <LatestRestorableTime>2011-05-23T06:50:00Z</LatestRestorableTime>
        <Engine>mysql</Engine>
        <PendingModifiedValues/>
        <BackupRetentionPeriod>1</BackupRetentionPeriod>
        <MultiAZ>false</MultiAZ>
        <LicenseModel>general-public-license</LicenseModel>
        <DBInstanceStatus>available</DBInstanceStatus>
        <EngineVersion>5.1.50</EngineVersion>
        <Endpoint>
          <Port>3306</Port>
          <Address>bobloblawlawblog01.cu7u2t4uz396.us-east-1.rds.amazonaws.com</Address>
        </Endpoint>
        <DBInstanceIdentifier>bobloblawlawblog01</DBInstanceIdentifier>
        <DBName>lawblog</DBName>
        <DBParameterGroups>
          <DBParameterGroup>
            <ParameterApplyStatus>in-sync</ParameterApplyStatus>
            <DBParameterGroupName>default.mysql5.1</DBParameterGroupName>
          </DBParameterGroup>
        </DBParameterGroups>
        <DBSecurityGroups>
          <DBSecurityGroup>
            <Status>active</Status>
            <DBSecurityGroupName>default</DBSecurityGroupName>
          </DBSecurityGroup>
        </DBSecurityGroups>
        <PreferredBackupWindow>00:00-00:30</PreferredBackupWindow>
        <AutoMinorVersionUpgrade>true</AutoMinorVersionUpgrade>
        <PreferredMaintenanceWindow>sat:07:30-sat:08:00</PreferredMaintenanceWindow>
        <AvailabilityZone>us-east-1a</AvailabilityZone>
        <InstanceCreateTime>2011-05-23T06:06:43.110Z</InstanceCreateTime>
        <AllocatedStorage>10</AllocatedStorage>
        <OptionGroupMemberships>
          <OptionGroupMembership>
            <OptionGroupName>default.mysql5.1</OptionGroupName>
            <Status>in-sync</Status>
          </OptionGroupMembership>
        </OptionGroupMemberships>
        <DBInstanceClass>db.m1.large</DBInstanceClass>
        <MasterUsername>master</MasterUsername>
        <PubliclyAccessible>false</PubliclyAccessible>
      </DBInstance>
    </DBInstances>
  </DescribeDBInstancesResult>
  <ResponseMetadata>
    <RequestId>9135fff3-8509-11e0-bd9b-a7b1ece36d51</RequestId>
  </ResponseMetadata>
</DescribeDBInstancesResponse>
`

var CreateDBInstanceExample1 = `
<CreateDBInstanceResponse xmlns="http://rds.amazonaws.com/doc/2013-09-09/">
  <CreateDBInstanceResult>
    <DBInstance>
      <BackupRetentionPeriod>1</BackupRetentionPeriod>
      <MultiAZ>false</MultiAZ>
      <DBInstanceStatus>creating</DBInstanceStatus>
      <VpcSecurityGroups/>
      <DBInstanceIdentifier>bobloblawlawblog01</DBInstanceIdentifier>
      <PreferredBackupWindow>01:24-01:54</PreferredBackupWindow>
      <PreferredMaintenanceWindow>wed:02:47-wed:03:17</PreferredMaintenanceWindow>
      <AvailabilityZone>us-east-1a</AvailabilityZone>
      <ReadReplicaDBInstanceIdentifiers/>
      <Engine>mysql</Engine>
      <PendingModifiedValues>
        <MasterUserPassword>****</MasterUserPassword>
      </PendingModifiedValues>
      <LicenseModel>general-public-license</LicenseModel>
      <EngineVersion>5.6.13</EngineVersion>
      <DBParameterGroups>
        <DBParameterGroup>
          <ParameterApplyStatus>in-sync</ParameterApplyStatus>
          <DBParameterGroupName>default.mysql5.6</DBParameterGroupName>
        </DBParameterGroup>
      </DBParameterGroups>
      <OptionGroupMemberships>
        <OptionGroupMembership>
          <OptionGroupName>default:mysql-5-6</OptionGroupName>
          <Status>in-sync</Status>
        </OptionGroupMembership>
      </OptionGroupMemberships>
      <PubliclyAccessible>true</PubliclyAccessible>
      <DBSecurityGroups>
        <DBSecurityGroup>
          <Status>active</Status>
          <DBSecurityGroupName>default</DBSecurityGroupName>
        </DBSecurityGroup>
      </DBSecurityGroups>
      <AutoMinorVersionUpgrade>false</AutoMinorVersionUpgrade>
      <AllocatedStorage>5</AllocatedStorage>
      <MasterUsername>bobloblaw</MasterUsername>
      <DBInstanceClass>db.t1.micro</DBInstanceClass>
    </DBInstance>
  </CreateDBInstanceResult>
  <ResponseMetadata>
    <RequestId>25a74649-8c57-11e3-b457-75a518426ed7</RequestId>
  </ResponseMetadata>
</CreateDBInstanceResponse>
`
